### ISSUE TITLE
Plugin doesn't save any data

### ISSUE THREAD

**Issue by holdav** [wakatime/brackets-wakatime#3] opened 2015-09-02 13:12 UTC
Hello,

I installed Brackets Wakatime plugin, create account at wakatime.com, pasate API key into Brackets plugin but after a day of working in Brackets no data wasn't save into wakatime.com. When I logged at wakatime.com there are no data shown, only "You logged 0 minutes". 

How can I debugg this problem?

Thank you.

**Comment by alanhamlett** [comment] 2015-09-02 15:48
You can open the dev tools to see the Brackets console. Also check the Networking dev tools tab to make sure the heartbeat is being sent without error.

![brackets-dev-tools](https://cloud.githubusercontent.com/assets/522344/9636256/5e052f72-514f-11e5-803a-51de6ee7de0e.png)

**Comment by holdav** [comment] 2015-09-02 16:10
Console in DevTools shows me only this warning, no errors:

"Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.<anonymous> (file:///home/holdav/.config/Brackets/extensions/user/brackets-wakatime/main.js:91:5) "

In Network tab, there are no errors too.

**Comment by alanhamlett** [comment] 2015-09-02 16:29
Oh thanks, it's fixed in v.1.0.5.

**Comment by holdav** [comment] 2015-09-02 17:13
Ok, thanks, in new version, there is no warning but after 20 minutes of using Brackets there are still no statistics at wakatime.com. Only thing which should cause problem is API key, it is only thing which me as a user entered and I entered is well, I checked API key many times. So what now? How can I find out what is wrong? Should you for example integrate into your plugin some info about Wakatime user (via API key)? Or something what can tell me, where is problem. I'm not probably connecting to wakatime.com or something like that.

**Comment by alanhamlett** [comment] 2015-09-02 18:03
You can check your last plugin from https://wakatime.com/api/v1/users/current but first you should check the Networking tab in `Debug` -> `Show Developer Tools` -> `Networking` and make sure the api is responding with a `201` status code.

Can you also make sure to use v1.0.6 of the plugin, because there was a bug in v1.0.5 that would prevent logging.

**Comment by holdav** [comment] 2015-09-02 19:11
I use plugin v1.0.6. 

In Netwok there are no requests from WakaTime plugin.

Data from https://wakatime.com/api/v1/users/current:

"last_heartbeat": "2015-08-07T13:36:33Z",
    "last_plugin": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.80 Safari/537.36 brackets-wakatime/1.0.4",
    "last_plugin_name": "Brackets",

Which means that in past (2015-08-07) plugin was probably working, but now it isn't.

I'm out of ideas now.

**Comment by alanhamlett** [comment] 2015-09-02 20:17
Just to make sure the plugin detected activity, can you save a file in Brackets then check the Networking tab?

I've tested the plugin on OS X, but you're using Linux correct? I'll test in Linux later today and see if I can reproduce this.

**Comment by holdav** [comment] 2015-09-02 21:02
I did that already. After save or any other activity in Brackets, no request isn't shown in Network tab. (No requests captured. Reload the page to see detailed information on the network activity.(after reload, there is still same message))

Yes, I use Ubuntu 14.04. I will test it also in Windows to be able to compare results and find out if this is crossplatform problem or not.

**Comment by holdav** [comment] 2015-09-02 21:37
Heartbeat request is calling on Windows 8.1, so the problem will be on Linux. Run it on Linux, if you can and you should have the same problem.

**Comment by holdav** [comment] 2015-09-02 21:51
I have also noticed that on Windows in Network tab of DevTools there are around 20 requests after switch to another project in Brackets. On Linux there are no requests, simply blank log.

**Comment by alanhamlett** [comment] 2015-09-03 02:26
I wasn't able to reproduce this in Linux (Ubuntu 15.04). The heartbeats were being sent correctly in my VM. Did you restart Brackets after installing WakaTime v1.0.6?

Note: The developer tools wouldn't open in Linux, but using Chrome and going to [http://localhost:9234](http://localhost:9234) is a workaround.

**Comment by holdav** [comment] 2015-09-03 19:50
I have looked into source codes of a plugin and start debugging and I find out one interesting thing, sendHeartbeat() isn't calling because handleAction() do not pass through this condition "if (!fileIsIgnored(file.fullPath))" and fileIsIgnored() returns me true, because in prefs.get("ignore") there is "var" folder in which I have got all localhost projects, so I looked into preferences file brackets.json and there is: 

"WakaTime.ignore": [
        "^/var/",
        "^/tmp/",
        "^/private/"
 ],

Why is this there? I guess, it has got certainly connection with this thread https://github.com/wakatime/brackets-wakatime/issues/1, right?

Please make new version of plugin in which is removed this line from main.js

prefs.definePreference("ignore", "array", ["^/var/", "^/tmp/", "^/private/"]);

This line kills most of Linux users. I don't see any reason to have "var" folder as an default ignored folder. This folder is used by Apache (var/www).

Thanks a lot for your help!

**Comment by alanhamlett** [comment] 2015-09-03 21:18
The reason for that line is to prevent logging time against log files. According to the standard linux filesystem structure, files in `/var` should only be log files, spool files, and temporary files:
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
This means when following linux conventions, projects shouldn't be stored in `/var`.

I'll go ahead and remove `/var` from the default ignored list and people wanting it back can add it to their `brackets.json`.

If you want to start logging now without waiting for the next release, you can open your `brackets.json` settings file and add this line:
`"WakaTime.ignore": [],`

That will overwrite the default ignored paths.

**Comment by alanhamlett** [comment] 2015-09-03 21:21
Just released v1.0.7 without `/var` in the default ignored paths preference.

**Closed by alanhamlett** 2015-09-03 21:21 UTC

**Comment by holdav** [comment] 2015-09-04 11:48
Thank you, it's working now!

/var should be folder with logs however in case of Apache it isn't. Apache really uses /var folder as a default folder for localhost and I think that most of Linux user doesn't change this path.
